INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('540feb7e-ba82-48fb-8028-9445662d4569', 'Vacuumancy', 'Vacuumancy', 'Mana', 0, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('576c1880-eb89-42f9-a63a-1240e49a3699', 'Pathfinding', 'Pathfinding', 'Pathfinding', 0, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('57d786b3-b2a4-4e93-a8be-8f4c0495cf65', 'Character Abilities', 'Character Abilities', 'unknown', 0, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('5be8e305-c082-45a6-9e55-d42406cc809a', 'Healer Augmentation Spec', 'Augmentation', 'Augmentation', 0, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('5e021c3a-025c-495f-9d97-32969f253d75', 'Illusions', 'Illusions', 'Light', 0, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('5e233c19-7e50-4649-a645-458026936b69', 'Vivification', 'Vivification', 'Spirit Magic', 0, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('5f1bcc9b-bc55-4c78-ba46-01feb8a26149', 'Arboreal Path Spec Pet', 'Arboreal Path Spec Pet', 'Arboreal Path Spec Pet', 1, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('60e2953c-22b8-45b4-9348-f081656bb5d6', 'Enchantment', 'Enchantment', 'Enchantments', 1, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('6423c9b3-c07e-4947-b13b-970063e92207', 'Soulrending', 'Soulrending', 'Soulrending', 0, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('64ab909e-d5fc-4cd9-8f20-c130ca532953', 'PetBuff', 'PetBuff', 'PetBuff', 1, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('66111f5d-4594-4af0-ab25-8a77a046e474', 'Holism', 'Holism', 'Mana', 0, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('670086b1-1019-498e-ba6b-8252b5f0020c', 'DefensiveProc', 'DefensiveProc', 'unknown', 0, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('688c400c-8442-418d-99eb-593fb9dc076d', 'Shaman Augmentation Spec', 'Augmentation', 'Augmentation', 0, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('6aefde22-85e2-4091-a028-42e218dfad50', 'Bard Music Spec', 'Music', 'Music', 0, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('6bf6282b-c2ee-4bfe-9db2-7377a2189de5', 'Druid Nature Magic', 'Nature', 'Nature', 1, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('6eade47d-fa2e-4770-9c16-2f740356c4a3', 'Bard Nurture Spec', 'Nurture', 'Nurture', 0, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('73a1767d-12ce-4732-b66d-b0e8f5ad01d8', 'Way of the Eclipse', 'Way of the Eclipse', 'Void', 1, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('7599d8c0-7633-441e-95ac-540ebf6e60c9', 'OffensiveProc', 'OffensiveProc', 'unknown', 0, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('7c4877a7-9ea9-483a-b533-8de596f76653', 'Verdant Path', 'Verdant Path', 'Verdant Path', 1, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('7de54848-ac92-4aa9-964c-db1242e9cf21', 'Creeping Path', 'Creeping Path', 'Creeping Path', 1, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('7e181ca2-49c1-4870-8e0d-36c9c2da4591', 'Runes of Suppression', 'Runes of Suppression', 'Suppression', 0, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('82f26c67-aea6-480c-9a79-f1ef2c829c02', 'Empowering', 'Empowering', 'Mana', 0, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('86f82215-435f-4f44-b2b6-5141997b4a8d', 'UnderhillAllyHeal', 'UnderhillAllyHeal', 'UnderhillAllyHeal', 1, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('884e6127-bc05-4d54-9ca2-34c7fb121d48', 'Regrowth Bard Spec', 'Regrowth', 'Regrowth', 0, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('8aa128bc-a170-442e-b13c-93f6de4ec64b', 'Instruments', 'Instruments', 'Instruments', 0, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('8dc3ae87-1bd0-43be-96af-840c5b3350d0', 'Friar Enhancement Spec', 'Enhancement', 'Enhancement', 0, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('8df059eb-e74d-4fbf-9f6b-2f29093db5be', 'Death Servant', 'Death Servant', 'Death Servant', 1, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('8e0e2c61-5876-4bbb-9d57-b20e1edbf586', 'Spirit Dimming', 'Spirit Dimming', 'Darkness', 0, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('8fb5c9bd-36f6-4bcb-8206-f7b3c7d746e6', 'AllyHealOverTime', 'AllyHealOverTime', 'AllyHealOverTime', 1, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('905eb758-fb94-486f-9284-389419822408', 'Pyromancy', 'Pyromancy', 'Fire Magic', 0, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('99606f58-54fb-4cd7-8c8f-cc34730186b6', 'Path of Earth', 'Path of Earth', 'Earth Magic', 1, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('9f47c113-40b2-4ca9-8cee-6c17cbc51026', 'Shaman Mend Spec', 'Mending', 'Mending', 0, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('a11b2d0c-e088-4709-86e5-17778d0e389b', 'Creeping Path Spec', 'Creeping Path Spec', 'Creeping Path', 0, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('a28dc84f-932a-4a43-bd0d-2bb1efa34947', 'Nightshade', 'Nightshade Magic', 'Nightshade Magic', 1, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('a6410137-01d1-4de9-aa00-f8a314d403e9', 'Runes of Destruction', 'Runes of Destruction', 'Runecarving', 0, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('a6be4a99-975a-49a6-9dc9-8a0ef5308d1e', 'Enhancement', 'Enhancement', 'Enhancement', 1, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('a8c694dd-3ce0-4f01-8a80-5ede824b831f', 'Item Effects', 'Item Effects', 'unknown', 0, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('abcf0013-f450-42fc-bc67-18361abff643', 'Verdant Path Pet', 'Verdant Path Pet', 'Verdant Path Pet', 1, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('adc2901f-5ac8-439a-b421-1b5b40174d3b', 'Calefaction', 'Calefaction', 'Earth Magic', 0, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('ade57461-0470-45e0-886f-0cbaad9301f4', 'Mundane Poisons', 'Mundane Poisons', 'unknown', 1, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('ae8b2b56-5212-4413-976e-29c4d90397c9', 'Augmentation', 'Augmentation', 'Augmentation', 1, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('afec1272-04f8-44aa-9d71-a643448e3354', 'Suppression', 'Suppression', 'Suppression', 1, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('b025b99a-13ad-4447-9baf-b55fa9e6f706', 'Nurture Warden Spec', 'Nurture Warden Spec', 'Nurture', 0, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('b30ceac8-212d-49f6-8321-2123258c0932', 'Stormcalling', 'Stormcalling', 'Stormcalling', 0, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('b4b5afc1-529f-4881-b4b4-1801fb903ebc', 'Regrowth', 'Regrowth', 'Regrowth', 1, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('b5805802-411a-42b7-946e-331e4822dbb6', 'Regrowth Warden Spec', 'Regrowth Warden Spec', 'Regrowth', 0, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('b8b522b0-6b91-473c-a573-7a83a42fa4da', 'Pacification', 'Pacification', 'Pacification', 1, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('b8c844d5-eceb-45f4-9457-f3888be953a4', 'Telekinesis', 'Telekinesis', 'Matter Magic', 0, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('b98a21a8-de37-43a9-bf59-4d9f824f3e96', 'Vampiiric Embrace', 'Vampiiric Embrace', 'Vampiiric Embrace', 0, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('b992a0e2-9081-4d6a-98e4-94afcc060df5', 'Dementia', 'Dementia', 'Dementia', 0, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('b9b04256-b611-455d-9786-066c710b6952', 'Painworking Spec', 'Painworking Mastery', 'Painworking', 0, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('c3c3311b-d099-4737-b6c3-a1be713b4472', 'Smiting', 'Smite', 'Smite', 1, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('cb22f8ff-b187-4f2c-a6fe-548ea47c87c4', 'Healer Mending Spec', 'Mending', 'Mending', 0, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('cbafc4f3-da39-4f1d-87fa-a53ded1c2b00', 'Regrowth Druid Spec', 'Druid', 'Regrowth', 0, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('ccfa9bb6-31bf-40a4-995f-58010dc1acea', 'Essence Manipulation', 'Essence Manipulation', 'Body Magic', 0, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('ce5587c8-1d7d-4902-ac51-c5c7e9dcaf49', 'Spirit Animation', 'Spirit Animation', 'Spirit Magic', 1, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('cfa36a6e-df75-4df8-82cd-8f4847fdcf73', 'Bedazzling', 'Bedazzling', 'Light', 0, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('champion_spells', 'Champion Abilities', 'Champion Abilities', 'Champion Abilities', 1, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('d0b3025b-fb46-4c3f-b60f-2a7f84ba0873', 'Valewalker Arb Path Spec', 'Aborial Mastery', 'Arboreal Path', 0, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('d12b5654-2dd1-4685-b205-ed00e8244a93', 'Shadow Mastery', 'Shadow Mastery', 'Shadow Mastery', 0, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('d28091b0-c953-4b66-a353-bc4383b91f99', 'Matter', 'Matter', 'Matter Magic', 1, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('d29733c3-19e7-4453-a66e-5b216b2b9d84', 'Bone Warriors', 'Bone Warriors', 'Bone Army', 0, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('d3072458-007a-4f81-b172-206176f5f57d', 'Creeping Path Pet', 'Creeping Path Pet', 'Creeping Path Pet', 1, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('d3f9b501-6e20-4b56-85b3-7acb16f970bb', 'Shadow Control', 'Shadow Control', 'Light', 0, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('d454a084-1554-45e9-83a2-230d666ad04f', 'Summoning', 'Summoning', 'Summoning', 1, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('d94b34d7-08b5-4c74-b9bb-a10162d02219', 'Path of Air', 'Path of Air', 'Wind Magic', 1, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('db854fd6-d348-427e-9acc-fceae173e1ff', 'Disorientation', 'Disorientation', 'Body Magic', 0, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('dde5bfac-7c25-4c3d-8347-152c0ed964fa', 'Painworking', 'Painworking', 'Painworking', 1, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('Dragon Magic', 'Dragon Magic', 'Dragon Magic', 'Dragon Magic', 1, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('e2ca94e1-2db1-4afd-90d7-0dc749f8f091', 'Bone Mystics', 'Bone Mystics', 'Darkness', 0, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('e32e5564-2bd2-4bbd-b63a-63793569f507', 'Path of Fire', 'Path of Fire', 'Fire Magic', 1, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('e90b8484-1a57-4bfb-bc51-d3574b3559fd', 'Subterranean Incantations', 'Subterranean', 'Subterranean', 1, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('ec28f359-e49f-40cf-9c12-f851afe5d069', 'Matter Manipulation', 'Matter Manipulation', 'Matter Magic', 0, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('edd85234-c777-4203-9a11-9ade5d0c8ce2', 'Creeping Path Spec Pet', 'Arboreal Path Spec Pet', 'Arboreal Path Spec Pet', 1, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('edfb0701-ce61-4955-8987-8309fd1f8fe1', 'Way of the Sun', 'Way of the Sun', 'Light', 1, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('eed7c39c-ca3f-4eae-aa40-dad7659c35d2', 'Body Destruction', 'Body Destruction', 'Body Magic', 1, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('eee722a1-f56f-4fef-8f06-642c2a7fb4e3', 'Darkness', 'Darkness', 'Darkness', 1, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('f00f0959-b47c-45ef-8cb4-75f67c429a1a', 'Savagery', 'Savagery', 'Savagery', 0, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('f3b6c98a-0d60-45d6-87b7-aab78c7fdc1d', 'Rebirth (Cleric)', 'Rejuvenation', 'Rejuvenation', 0, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('f41e474b-fdd5-486f-8602-a4f32dad8eab', 'Combat Style Effects', 'Combat Style Effects', 'unknown', 0, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('f6e94717-6c42-4a67-8d86-d9b5867c5244', 'Way of the Moon', 'Way of the Moon', 'Mana', 1, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('f79175af-0799-401b-83e7-e11052bbd9d3', 'Vapormancy', 'Vapormancy', 'Wind Magic', 0, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('f90f73f0-9c7d-42ea-9ad9-dd6e6a48da5a', 'Bard Music', 'Music', 'Music', 1, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('fa94ac49-db4c-4fed-a973-5879d818ffa3', 'Player poisons', 'Player poisons', 'unknown', 1, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('fbab1802-dff5-4afa-adde-3a9cc671ef13', 'Verdant Path Spec', 'Verdant Mastery', 'Verdant Path', 0, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('fbbb7687-63bf-45fa-9c23-19974dd0532b', 'AirElementalStun', 'AirElementalStun', 'AirElementalStun', 1, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('fd197db1-df0c-4cae-8cce-888c00c3db01', 'Nurture', 'Nurture', 'Nurture', 1, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('ffe965ad-6347-4844-9e4a-8eb99c4935a7', 'Refrigeration', 'Refrigeration', 'Cold Magic', 0, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('Fulltank Abilities', 'Fulltank Abilities', 'Fulltank Abilities', 'Fulltank Abilities', 1, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('hd4574573456hfgh', 'Cursing Spec', 'Cursing Spec', 'Cursing', 0, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('HereticBaselineEnhancement', 'Heretic Enhancement', 'Enhancement', 'Enhancement', 1, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('Mauler_Aura_Manipulation', 'Aura Manipulation', 'Aura Manipulation', 'Aura Manipulation', 0, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('Mauler_Magnetism', 'Magnetism', 'Magnetism', 'Magnetism', 0, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('Mauler_Power_Strikes', 'Power Strikes', 'Power Strikes', 'Power Strikes', 0, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('ML_Banelord', 'Banelord', 'Banelord', 'unknown', 0, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('ML_Banelord_1', 'ML1 Banelord', 'ML1 Banelord', 'unknown', 1, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('ML_Banelord_10', 'ML10 Banelord', 'ML10 Banelord', 'unknown', 1, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('ML_Banelord_2', 'ML2 Banelord', 'ML2 Banelord', 'unknown', 1, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('ML_Banelord_3', 'ML3 Banelord', 'ML3 Banelord', 'unknown', 1, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('ML_Banelord_4', 'ML4 Banelord', 'ML4 Banelord', 'unknown', 1, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('ML_Banelord_5', 'ML5 Banelord', 'ML5 Banelord', 'unknown', 1, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('ML_Banelord_6', 'ML6 Banelord', 'ML6 Banelord', 'unknown', 1, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('ML_Banelord_7', 'ML7 Banelord', 'ML7 Banelord', 'unknown', 1, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('ML_Banelord_8', 'ML8 Banelord', 'ML8 Banelord', 'unknown', 1, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('ML_Banelord_9', 'ML9 Banelord', 'ML9 Banelord', 'unknown', 1, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('ML_Battlemaster', 'Battlemaster', 'Battlemaster', 'unknown', 0, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('ML_Battlemaster_1', 'ML1 Battlemaster', 'ML1 Battlemaster', 'unknown', 1, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('ML_Battlemaster_10', 'ML10 Battlemaster', 'ML10 Battlemaster', 'unknown', 1, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('ML_Battlemaster_2', 'ML2 Battlemaster', 'ML2 Battlemaster', 'unknown', 1, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('ML_Battlemaster_3', 'ML3 Battlemaster', 'ML3 Battlemaster', 'unknown', 1, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('ML_Battlemaster_4', 'ML4 Battlemaster', 'ML4 Battlemaster', 'unknown', 1, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('ML_Battlemaster_5', 'ML5 Battlemaster', 'ML5 Battlemaster', 'unknown', 1, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('ML_Battlemaster_6', 'ML6 Battlemaster', 'ML6 Battlemaster', 'unknown', 1, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('ML_Battlemaster_7', 'ML7 Battlemaster', 'ML7 Battlemaster', 'unknown', 1, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('ML_Battlemaster_8', 'ML8 Battlemaster', 'ML8 Battlemaster', 'unknown', 1, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('ML_Battlemaster_9', 'ML9 Battlemaster', 'ML9 Battlemaster', 'unknown', 1, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('ML_Convoker', 'Convoker', 'Convoker', 'unknown', 0, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('ML_Convoker_1', 'ML1 Convoker', 'ML1 Convoker', 'unknown', 1, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('ML_Convoker_10', 'ML10 Convoker', 'ML10 Convoker', 'unknown', 1, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('ML_Convoker_2', 'ML2 Convoker', 'ML2 Convoker', 'unknown', 1, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('ML_Convoker_3', 'ML3 Convoker', 'ML3 Convoker', 'unknown', 1, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('ML_Convoker_4', 'ML4 Convoker', 'ML4 Convoker', 'unknown', 1, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('ML_Convoker_5', 'ML5 Convoker', 'ML5 Convoker', 'unknown', 1, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('ML_Convoker_6', 'ML6 Convoker', 'ML6 Convoker', 'unknown', 1, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('ML_Convoker_7', 'ML7 Convoker', 'ML7 Convoker', 'unknown', 1, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('ML_Convoker_8', 'ML8 Convoker', 'ML8 Convoker', 'unknown', 1, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('ML_Convoker_9', 'ML9 Convoker', 'ML9 Convoker', 'unknown', 1, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('ML_Perfecter', 'Perfecter', 'Perfecter', 'unknown', 0, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('ML_Perfecter_1', 'ML1 Perfecter', 'ML1 Perfecter', 'unknown', 1, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('ML_Perfecter_10', 'ML10 Perfecter', 'ML10 Perfecter', 'unknown', 1, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('ML_Perfecter_2', 'ML2 Perfecter', 'ML2 Perfecter', 'unknown', 1, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('ML_Perfecter_3', 'ML3 Perfecter', 'ML3 Perfecter', 'unknown', 1, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('ML_Perfecter_4', 'ML4 Perfecter', 'ML4 Perfecter', 'unknown', 1, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('ML_Perfecter_5', 'ML5 Perfecter', 'ML5 Perfecter', 'unknown', 1, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('ML_Perfecter_6', 'ML6 Perfecter', 'ML6 Perfecter', 'unknown', 1, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('ML_Perfecter_7', 'ML7 Perfecter', 'ML7 Perfecter', 'unknown', 1, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('ML_Perfecter_8', 'ML8 Perfecter', 'ML8 Perfecter', 'unknown', 1, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('ML_Perfecter_9', 'ML9 Perfecter', 'ML9 Perfecter', 'unknown', 1, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('ML_Sojourner', 'Sojourner', 'Sojourner', 'unknown', 0, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('ML_Sojourner_1', 'ML1 Sojourner', 'ML1 Sojourner', 'unknown', 1, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('ML_Sojourner_10', 'ML10 Sojourner', 'ML10 Sojourner', 'unknown', 1, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('ML_Sojourner_2', 'ML2 Sojourner', 'ML2 Sojourner', 'unknown', 1, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('ML_Sojourner_3', 'ML3 Sojourner', 'ML3 Sojourner', 'unknown', 1, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('ML_Sojourner_4', 'ML4 Sojourner', 'ML4 Sojourner', 'unknown', 1, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('ML_Sojourner_5', 'ML5 Sojourner', 'ML5 Sojourner', 'unknown', 1, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('ML_Sojourner_6', 'ML6 Sojourner', 'ML6 Sojourner', 'unknown', 1, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('ML_Sojourner_7', 'ML7 Sojourner', 'ML7 Sojourner', 'unknown', 1, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('ML_Sojourner_8', 'ML8 Sojourner', 'ML8 Sojourner', 'unknown', 1, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('ML_Sojourner_9', 'ML9 Sojourner', 'ML9 Sojourner', 'unknown', 1, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('ML_Spymaster', 'Spymaster', 'Spymaster', 'unknown', 0, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('ML_Spymaster_1', 'ML1 Spymaster', 'ML1 Spymaster', 'unknown', 1, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('ML_Spymaster_10', 'ML10 Spymaster', 'ML10 Spymaster', 'unknown', 1, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('ML_Spymaster_2', 'ML2 Spymaster', 'ML2 Spymaster', 'unknown', 1, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('ML_Spymaster_3', 'ML3 Spymaster', 'ML3 Spymaster', 'unknown', 1, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('ML_Spymaster_4', 'ML4 Spymaster', 'ML4 Spymaster', 'unknown', 1, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('ML_Spymaster_5', 'ML5 Spymaster', 'ML5 Spymaster', 'unknown', 1, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('ML_Spymaster_6', 'ML6 Spymaster', 'ML6 Spymaster', 'unknown', 1, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('ML_Spymaster_7', 'ML7 Spymaster', 'ML7 Spymaster', 'unknown', 1, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('ML_Spymaster_8', 'ML8 Spymaster', 'ML8 Spymaster', 'unknown', 1, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('ML_Spymaster_9', 'ML9 Spymaster', 'ML9 Spymaster', 'unknown', 1, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('ML_Stormlord', 'Stormlord', 'Stormlord', 'unknown', 0, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('ML_Stormlord_1', 'ML1 Stormlord', 'ML1 Stormlord', 'unknown', 1, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('ML_Stormlord_10', 'ML10 Stormlord', 'ML10 Stormlord', 'unknown', 1, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('ML_Stormlord_2', 'ML2 Stormlord', 'ML2 Stormlord', 'unknown', 1, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('ML_Stormlord_3', 'ML3 Stormlord', 'ML3 Stormlord', 'unknown', 1, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('ML_Stormlord_4', 'ML4 Stormlord', 'ML4 Stormlord', 'unknown', 1, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('ML_Stormlord_5', 'ML5 Stormlord', 'ML5 Stormlord', 'unknown', 1, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('ML_Stormlord_6', 'ML6 Stormlord', 'ML6 Stormlord', 'unknown', 1, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('ML_Stormlord_7', 'ML7 Stormlord', 'ML7 Stormlord', 'unknown', 1, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('ML_Stormlord_8', 'ML8 Stormlord', 'ML8 Stormlord', 'unknown', 1, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('ML_Stormlord_9', 'ML9 Stormlord', 'ML9 Stormlord', 'unknown', 1, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('ML_Warlord', 'Warlord', 'Warlord', 'unknown', 0, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('ML_Warlord_1', 'ML1 Warlord', 'ML1 Warlord', 'unknown', 1, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('ML_Warlord_10', 'ML10 Warlord', 'ML10 Warlord', 'unknown', 1, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('ML_Warlord_2', 'ML2 Warlord', 'ML2 Warlord', 'unknown', 1, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('ML_Warlord_3', 'ML3 Warlord', 'ML3 Warlord', 'unknown', 1, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('ML_Warlord_4', 'ML4 Warlord', 'ML4 Warlord', 'unknown', 1, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('ML_Warlord_5', 'ML5 Warlord', 'ML5 Warlord', 'unknown', 1, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('ML_Warlord_6', 'ML6 Warlord', 'ML6 Warlord', 'unknown', 1, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('ML_Warlord_7', 'ML7 Warlord', 'ML7 Warlord', 'unknown', 1, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('ML_Warlord_8', 'ML8 Warlord', 'ML8 Warlord', 'unknown', 1, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('ML_Warlord_9', 'ML9 Warlord', 'ML9 Warlord', 'unknown', 1, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('necro_pet_insta_spells', 'Necro Pet Insta Spells', 'Necro Pet Insta Spells', 'unknown', 1, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('new_archery', 'Archery', 'Archery', 'Archery', 0, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('Sorts des dieux', 'Sorts des dieux', 'Sorts des dieux', 'Sorts des dieux', 1, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('StealtherAbility1', 'InfiltratorAbilities', 'Abilities', 'unknown', 1, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('StealtherAbility2', 'ShadowbladeAbilities', 'Abilities', 'unknown', 1, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('StealtherAbility3', 'NightshadeAbilities', 'Abilities', 'unknown', 1, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('valewalkerarborialpathbase', 'Valewalker Arboreal Path Base', 'Arboreal Path', 'Arboreal Path', 1, 'Public_DB');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('0012d9f1-5d79-4899-931d-13a08a479152', 'Verdant Path Spec Pet', 'Verdant Path Spec Pet', 'Verdant Path Spec Pet', 1, NULL);
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('0012d9f1-5d79-4899-931d-Banshee1', 'Spectral Force', 'Spectral Force', 'Spectral Guard', 1, NULL);
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('0012d9f1-5d79-4899-931d-Banshee2', 'Spectral Guard', 'Spectral Guard', 'Spectral Guard', 0, NULL);
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('0012d9f1-5d79-4899-931d-Banshee4', 'Ethereal Shriek', 'Ethereal Shriek', 'Ethereal Shriek', 0, NULL);
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('0012d9f1-5d79-4899-931d-Banshee5', 'Phantasmal Wail', 'Phantasmal Wail', 'Phantasmal Wail', 0, NULL);
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('0012d9f1-5d79-4899-931d-Warlock1', 'Witchcraft', 'Witchcraft', 'Witchcraft', 0, NULL);
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('0012d9f1-5d79-4899-931d-Warlock2', 'Hexing', 'Hexing', 'Hexing', 0, NULL);
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('0012d9f1-5d79-4899-931d-Warlock3', 'Cursing', 'Cursing', 'Cursing', 1, NULL);
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('01ba6b21-19a5-448e-a26f-e093aa52ba4d', 'Valor', 'Valor', 'Valor', 0, NULL);
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('0566f58e-b63e-49a4-90b0-f2cda5227518', 'Deathsight Spec', 'Deathsight Mastery', 'Deathsight', 0, NULL);
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('05d51458-7809-41aa-9435-e31ce2d638fa', 'Bone Guardians', 'Bone Guardians', 'Suppression', 0, NULL);
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('0943d563-ee6e-4ec4-a25e-c7fcb3d0e734', 'Deathsight', 'Deathsight', 'Deathsight', 1, NULL);
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('0bcc891b-f510-40d8-90f4-bc1b4fea72af', 'Mind Mastery', 'Mind Mastery', 'Mentalism', 0, NULL);
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('0c3f1538-4346-4de7-b23f-ac31f5cf4cbd', 'SappLifeDrain', 'SappLifeDrain', 'SappLifeDrain', 1, NULL);
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('10788f8a-824c-4f6c-bbc4-42b23c14123b', 'Odin\'s Will', 'Odin\'s Will', 'Odin\'s Will', 0, NULL);
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('10bffda3-b94b-41bb-9a28-6920f5e436dd', 'Spirit Suppression', 'Spirit Suppression', 'Suppression', 0, NULL);
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('10e4d163-ba77-4676-918e-a20625b100e0', 'Arboreal Path', 'Arboreal Path', 'Arboreal Path', 1, NULL);
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('1234-1234-12345-12356a', 'Valkyrie Mending Spec', 'Mending', 'Mending', 0, NULL);
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('12509db6-5467-47c7-8aab-8d3584ce2c36', 'Runes of Darkness', 'Runes of Darkness', 'Darkness', 0, NULL);
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('14574d9b-f9c2-414b-b45b-46d22fbc5ff6', 'UnderhillCompanionDD', 'UnderhillCompanionDD', 'UnderhillCompanionDD', 1, NULL);
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('16257eab-6197-4c13-9b47-797064431918', 'Reserved Spells', 'Reserved Spells', 'unknown', 0, NULL);
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('16b111a9-d68f-4fb5-98f4-51c56a6a14d1', 'Bone Army', 'Bone Army', 'Bone Army', 1, NULL);
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('17ae407b-4bc0-440b-99f2-567910187ab6', 'Potions', 'Potions', 'unknown', 1, NULL);
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('1d5abcbd-2a2e-4af6-92c6-a81127948e45', 'Subterranean Spec', 'Subterranean', 'Subterranean', 0, NULL);
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('1dfb6c5a-2066-4b78-8270-7fdafefd1ab8', 'Druid Nurture Spec', 'Nurture', 'Nurture', 0, NULL);
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('1e6ba225-4234-42a0-bc2d-a5fb3eb184fa', 'Mending', 'Mending', 'Mending', 1, NULL);
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('22ebee8e-3d60-40ff-a87d-a7ad703e182e', 'Void Mastery', 'Void Mastery', 'Void', 0, NULL);
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('245525-432234-341324-a34254524', 'Mob Spells', 'Mob Spells', 'Mob Spells', 0, NULL);
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('25101e5a-a270-4f0f-9a81-598ea89cfc81', 'Pacification Spec', 'Pacification', 'Pacification', 0, NULL);
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('26124ce3-e322-42e3-a5ca-dceee8fcfae2', 'Mind Twisting', 'Mind Twisting', 'Mind Magic', 1, NULL);
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('29c0664a-bf64-4a62-89a1-7ddaad1c602e', 'Liquifaction', 'Liquifaction', 'Cold Magic', 0, NULL);
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('2a317de8-9b97-4b61-bd20-db63d8413d3b', 'Abrasion', 'Abrasion', 'Earth Magic', 0, NULL);
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('2cde1b93-66da-4eff-826d-548e1cb15900', 'Death Servant Spec', 'Death Servant Mastery', 'Death Servant', 0, NULL);
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('34666145-664f-4c73-83bc-20270836e998', 'Domination', 'Domination', 'Mind Magic', 0, NULL);
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('364db302-dbd9-4c51-a49e-55ec014cbf52', 'Chants', 'Chants', 'Chants', 0, NULL);
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('36f8a695-69ca-4450-80a6-375fb609a86e', 'Battlesongs', 'Battlesongs', 'Battlesongs', 0, NULL);
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('371c4e2d-9e45-4e3c-9bd4-dd33c80095d4', 'UnderhillZealotDD', 'UnderhillZealotDD', 'UnderhillZealotDD', 1, NULL);
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('373a4f4e-271e-47c3-9154-69ed9c241e8c', 'Heretic Rejuvenation Spec', 'Rejuvenation', 'Rejuvenation', 0, NULL);
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('3be21234-5500-4242-bbe5-74ba26d6c59e', 'Beastcraft', 'Beastcraft', 'Beastcraft', 0, NULL);
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('3cec3483-fb67-457e-8415-f83a26e0e7d4', 'Rebirth', 'Rejuvenation', 'Rejuvenation', 0, NULL);
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('425e1033-bd32-418f-9ff6-4f9d61953e88', 'Path of Ice', 'Path of Ice', 'Cold Magic', 1, NULL);
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('42877b66-aaa9-401b-8a33-2e640d25620d', 'Heretic Enhancement Spec', 'Enhancement', 'Enhancement', 0, NULL);
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('42d927a8-f59b-4c8c-aa3b-2c9e9c212384', 'Guardian Angel', 'Enhancement', 'Enhancement', 0, NULL);
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('4407da91-c260-4e74-ba98-8e8346b5ed3c', 'Runecarving', 'Runecarving', 'Runecarving', 1, NULL);
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('44ed1d48-cc12-4c3c-bf6c-cbefc13651fb', 'Rejuvenation', 'Rejuvenation', 'Rejuvenation', 1, NULL);
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('46094a29-06af-45f5-b5bf-b75f306383d4', 'Spirit Enhancement', 'Spirit Enhancement', 'Summoning', 0, NULL);
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('4636346-4356364243-sdfgadsgf-45634', 'Abilities Spells', 'Abilities Spells', 'Abilities Spells', 0, NULL);
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('4850f3b7-8285-4f40-aaf8-44b151ee2df7', 'Arboreal Mastery', 'Arboreal Mastery', 'Arboreal Path', 0, NULL);
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('49be4db8-2f4a-45f0-a73c-8573dc6a8a96', 'SpiritBladeturn', 'SpiritBladeturn', 'SpiritBladeturn', 1, NULL);
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('4aa3b666-616f-415b-be32-1fcca8129821', 'Enchantment Mastery', 'Enchantment Mastery', 'Enchantments', 0, NULL);
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('4ae35e7f-f24b-4270-b5c1-e0eabbb5c0f8', 'Mentalism', 'Mentalism', 'Mentalism', 1, NULL);
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('4f3aa7cd-d63e-4e8f-a7fe-76d7340b9159', 'Druid Nature Spec', 'Nature', 'Nature', 0, NULL);
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('511e76eb-e553-478a-94be-8f103c34d980', 'Terrible Hammer', 'Smite', 'Smite', 0, NULL);
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('52c82f4c-c5e6-4647-86d6-6bd545c40c17', 'Arboreal Path Pet', 'Arboreal Path Pet', 'Arboreal Path Pet', 1, NULL);
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('53bc0b84-e9f4-43ac-9543-acd7ad2ea959', 'IceElementalDD', 'IceElementalDD', 'IceElementalDD', 1, NULL);
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('dinberg1', 'Gift of Flame', 'Gift of Flame', 'Gift of Flame', 0, 'Mattermancer');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('dinberg2', 'Air Manipulation', 'Air Manipulation', 'Stealth', 0, 'Mattermancer');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('dinberg3', 'Manipulate Earth', 'Manipulate Earth', 'Manipulate Earth', 0, 'Mattermancer');
INSERT INTO `spellline` (`SpellLine_ID`, `KeyName`, `Name`, `Spec`, `IsBaseLine`, `PackageID`) VALUES ('dinberg4', 'Mattermancery', 'Mattermancery', 'Mattermancery', 0, 'Mattermancer');
